another version of hook. use only .git folder

diff --git a/script/checkBranchName b/script/checkBranchName
--- a/script/checkBranchName
+++ b/script/checkBranchName
@@ -1,17 +1,17 @@
-#!/bin/sh
-
-echo "Verifying the validity of the branch name"
-
-BRANCH=$(git rev-parse --abbrev-ref HEAD)
-
-if [[ $BRANCH == "master" ]]; then
-    exit 0
-fi
-
-REGEX="(bugfix|feature|hotfix|develop)\/[A-Z]+-[0-9]+\/[a-zA-Z0-9_-]+$"
-
-if ! [[ $BRANCH =~ $REGEX ]]; then
-  echo "Your commit was rejected due to invalid branch name"
-  echo "Please rename your branch following this template '(bugfix|feature|hotfix|develop)/task-id/a-Z0-9_-'"
-  exit 1
-fi
+##!/bin/sh
+#
+#echo "Verifying the validity of the branch name"
+#
+#BRANCH=$(git rev-parse --abbrev-ref HEAD)
+#
+#if [[ $BRANCH == "master" ]]; then
+#    exit 0
+#fi
+#
+#REGEX="(bugfix|feature|hotfix|develop)\/[A-Z]+-[0-9]+\/[a-zA-Z0-9_-]+$"
+#
+#if ! [[ $BRANCH =~ $REGEX ]]; then
+#  echo "Your commit was rejected due to invalid branch name"
+#  echo "Please rename your branch following this template '(bugfix|feature|hotfix|develop)/task-id/a-Z0-9_-'"
+#  exit 1
+#fi
